version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: get node repo
          command: wget -qO- https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - run:
          name: install node
          command: sudo apt-get install -y nodejs
      - run:
          name: Get aws cli
          command: sudo pip install awscli
      - run:
          name: Get aws sam
          command: sudo pip install aws-sam-cli
      - run:
          name: Setup config
          command: cp $env_name-config.sh config.sh
      - run:
          name: Install NPM deps
          command: npm install
      - run:
          name: Deploy
          command: npm run deploy

workflows:
  version: 2
  deploy-dev:
    jobs:
      - build:
          filters:
            tags:
              only: /^dev_backend.*/
            branches:
              ignore: /.*/
          context: dev